# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    # define required environment variables so that GitHub Actions can build
    # the application :)
    env:
      REDIS_URI: localhost
      REDIS_PORT: 6379
      DB_PROVIDER: postgres
      DB_URI: localhost
      DB_PORT: 5432
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      HOST: localhost
      PORT: 8532
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        coverage run -m pytest --verbose; coverage report --show-missing; coverage erase
